# Generated by Django 5.1.2 on 2024-10-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restonya',
            name='menu',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
