# Generated by Django 5.1.2 on 2024-10-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0002_restonya_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='restonya',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
