# Generated by Django 5.1.2 on 2024-10-25 18:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0006_alter_restonya_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resto_ID',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('restaurant', models.CharField(max_length=266)),
                ('rating', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='restonya',
            name='rating',
        ),
        migrations.AlterField(
            model_name='restonya',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
