# Generated by Django 5.1.2 on 2024-10-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0008_delete_resto_id_restonya_rating_alter_restonya_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restonya',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
