# Generated by Django 5.1.2 on 2024-10-25 19:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0010_resto_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resto_ID',
        ),
        migrations.AlterField(
            model_name='restonya',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
