# Generated by Django 5.1.2 on 2024-10-26 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0011_delete_resto_id_alter_restonya_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='restonya',
            name='harga',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restonya',
            name='jarak',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
