# Generated by Django 5.1.2 on 2024-10-27 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlistmenu', '0003_wishlistmenu_delete_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='wishlistmenu',
            name='menu_name',
        ),
        migrations.RemoveField(
            model_name='wishlistmenu',
            name='resto_name',
        ),
        migrations.AddField(
            model_name='wishlistmenu',
            name='menu_item',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlistmenu',
            name='wanted',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='wishlistmenu',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='wishlistmenu',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wishlistmenu.restaurant'),
            preserve_default=False,
        ),
    ]
