# Generated by Django 5.1.2 on 2024-10-27 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlistmenu', '0005_menuitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menulist', to='wishlistmenu.restaurant'),
        ),
    ]
