# Generated by Django 5.1.2 on 2024-10-27 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlistmenu', '0006_alter_menuitem_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='wishlistmenu.restaurant'),
        ),
        migrations.AlterField(
            model_name='wishlistmenu',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wishlistmenu.menuitem'),
        ),
    ]
