# Generated by Django 5.1.2 on 2024-10-27 01:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlistmenu', '0007_alter_menuitem_restaurant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(max_length=266)),
            ],
        ),
        migrations.RemoveField(
            model_name='wishlistmenu',
            name='menu_item',
        ),
        migrations.RemoveField(
            model_name='wishlistmenu',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='wishlistmenu',
            name='wanted',
        ),
        migrations.AddField(
            model_name='wishlistmenu',
            name='menu_wanted',
            field=models.CharField(blank=True, max_length=266, null=True),
        ),
        migrations.AddField(
            model_name='wishlistmenu',
            name='wanted_menu',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='wishlistmenu',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wishlistmenu',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
