# Generated by Django 5.1.2 on 2024-10-27 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlistmenu', '0008_menu_remove_wishlistmenu_menu_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=266)),
            ],
        ),
        migrations.AlterField(
            model_name='wishlistmenu',
            name='menu_wanted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wishlistmenu.menu'),
        ),
        migrations.AddField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='wishlistmenu.restaurant'),
            preserve_default=False,
        ),
    ]
