# Generated by Django 5.1.2 on 2024-10-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Makanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferensi', models.CharField(max_length=35)),
                ('menu', models.CharField(max_length=255)),
            ],
        ),
    ]
