# Generated by Django 5.1.2 on 2024-10-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipemakanan', '0003_alter_makanan_restoran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makanan',
            name='menu',
            field=models.CharField(max_length=1000),
        ),
    ]
