# Generated by Django 5.1.1 on 2024-10-22 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resto',
            old_name='restaurant_name',
            new_name='restaurant',
        ),
        migrations.AddField(
            model_name='resto',
            name='rating',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
