# Generated by Django 5.1.2 on 2024-10-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_rename_restaurant_name_resto_restaurant_resto_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.CharField(max_length=266)),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Resto',
        ),
    ]
