# Generated by Django 5.1.2 on 2024-10-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlistresto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resto',
            name='wanted_resto',
            field=models.BooleanField(default=False),
        ),
    ]
