# Generated by Django 5.1.2 on 2024-10-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlistresto', '0003_alter_resto_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
