# Generated by Django 5.1.2 on 2024-10-22 16:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlistresto', '0005_resto_user_alter_resto_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resto',
            name='user',
        ),
        migrations.RemoveField(
            model_name='resto',
            name='visited',
        ),
        migrations.RemoveField(
            model_name='resto',
            name='wanted_resto',
        ),
        migrations.AlterField(
            model_name='resto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='WishlistResto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wanted_resto', models.BooleanField(default=False)),
                ('visited', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
