# Generated by Django 5.1.2 on 2024-10-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlistresto', '0006_remove_resto_user_remove_resto_visited_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistresto',
            name='restaurant_wanted',
            field=models.CharField(blank=True, max_length=266, null=True),
        ),
    ]
