# Generated by Django 5.1.2 on 2024-10-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='harga',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='jarak',
            field=models.CharField(default=0, max_length=266),
            preserve_default=False,
        ),
    ]
