# Generated by Django 5.1.2 on 2024-10-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_restaurant_harga_restaurant_jarak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='jarak',
            field=models.FloatField(),
        ),
    ]
