# Generated by Django 5.1.2 on 2024-10-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_searchhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchhistory',
            old_name='search_query',
            new_name='nama',
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='jenis_makanan',
            field=models.CharField(default=0, max_length=266),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='rating',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
