# Generated by Django 5.1.2 on 2024-10-27 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0010_remove_searchhistory_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchHistory',
        ),
    ]
